config/routes.rb
Rails.application.routes.draw do

  root to: 'users#new'

  # serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
   resources :trips, param: :trip_id
   resources :messages  

  # if using update probably use patch? only changes the one field
  # have only got create and destroy attendees within the trip 
  resources :trips, except: [:index] do
    resources :attendees, only: [:create, :destroy]
    resources :messages, only: [:create, :destroy]

    resources :expenses, except: [:index, :new] do  
      resources :payees, only: [:create, :destroy]
      member do 
        get :inline_edit
      end
    end
  end
  
    # resources :sessions, except: [:index, :edit, :update]
  
    #users/new(register), users/edit(update email, etc.), users/show(user homepage)
    resources :users, only: [:new, :create, :edit, :show] 
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   get '/login' => 'users#new'
   post '/users' => 'users#create'
  
  #  get '/login' => 'sessions#new'
   post '/login' => 'sessions#create'
   get '/logout' => 'sessions#destroy'
  
  end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :payees
  has_many :attendees
  has_many :expenses
  has_many :trips, :through => :attendees
  has_many :messages

  validates :name, presence: true, length: { minimum: 1, maximum: 25 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }

  def self.authenticate_with_credentials( email, password )
    user = User.find_by_email(email.strip.downcase)
    if !user
      return nil
    elsif user.authenticate(password)
      return user
    else
      return nil
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_trip, only: [:show]
  
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @new_trip = Trip.new
    @user_as_attendees = Attendee.where(user_id: params[:id])
    @trip_types = [["Weekend Getaway", 1], ["Boys Trip", 2], ["Bachelorette", 3], ["Road Trip", 4], ["Adventure", 5], ["Other", 6]]
    @trips_of_user = @user.trips.order('start_date')
    if params[:id].to_i != current_user[:id].to_i
      redirect_to user_path(session[:user_id])
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { redirect_to '/login#login-register', notice: 'There was something wrong with your credentials' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      if User.exists?(params[:id])
        @user = User.find(params[:id])
      else
        redirect_to '/login'
      end
    end
    
    def set_trip
      if @trip
        @trip = Trip.find(params[:trip_id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :password_digest %>
    <%= form.text_field :password_digest, id: :user_password_digest %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_login_form.html.erb
<head>

	<script type="text/javascript">
		function scrollto(div) {
			document.getElementById(div).scrollIntoView(true);
		}
	</script>

	<script src="https://use.fontawesome.com/ac442f7ad2.js"></script>

</head>

<body style="background: linear-gradient(to bottom, #004d4d 0%, #004d4d 25%, #004d4d 33.5%,rgba(211, 191, 162, 0.25) 25%, rgba(211, 191, 162, 0.25) );">
	<div id="top-half">

		<h1 class="trekcheque">
			<i class="fa fa-car"></i> TREK CHEQUE<br>
		</h1>

		<div id="login-header">
			<% if current_user %>
				<span class="home-page-link"><%=link_to '| Profile Page', user_path(current_user.id)%></span>
			<% else %>
				<span onclick="scrollto('login-scroll');"> | Login | Register</span>
			<% end %>
			<span onclick="scrollto('about');"> | About |</span>
		</div>

	</div>
		<div class="trekcheque-brief">
			<hr>
			A travel app for friends: Simplifying your expenses, maximizing your time
			<hr>
		</div>	

		<div class="container" id="about" >
			<h2>ABOUT TREK CHEQUE</h2>
			<p>Trek Cheque helps take the stress out of your adventures - from sharing with friends in real-time chat to splitting expenses, Trek Cheque is your one stop spot to lay important trip details out for everyone to see. Trek Cheque helps you go from planning your trip details, such as dates, accommodation, and how many people to invite, to an easy to read, interactive trip page where you and your friends can confirm your spot, check how much accommodation would cost and split expenses. Once you have finished your trip Trek Cheque will even let you know who owes who what in the least number of transactions. </p>
		</div>	

		<div class="container" id="how-to" >
			<h2>HOW TO USE TREK CHEQUE</h2>
				<%=image_tag("Homepage.png") %>
			<p>To use Trek Cheque, simply register for an account and start creating trips! Each of the trips you join will show up on your home page for quick and easy access. To invite friends have them create an account and send them a link to your trip! They can click ‘Join Trip’ and get added as an attendee until the maximum amount of people have joined. Once you have started your trip, click ‘Trip Started’ and start tracking your expenses! The details you put in for accommodation will also be automatically calculated and added as an expense, but if this changes all expenses can be edited. When you have finished the trip click ‘End Trip’ and the amounts owed between you will be displayed!</p>
		</div>

	<div class="container" id="login-container" >

		<div class="row" id="login-row">

			<div id="login-register" class="login-register" >
				<div class="col-md-6 col-md-offset-3" id="login-scroll">
				<% if flash[:alert] %>
					<div class="alert alert-danger"><%= flash[:alert] %></div>
				<% end %>
					<div class="panel panel-login">
					
						<div class="panel-heading">
							<div class="row" role='tablist'>
								<div class="col-xs-6" role='presentation'>
									<a href="#login" id="login-form-link" aria-controls="login" role="tab" data-toggle="tab">Login</a>
								</div>
								<div class="col-xs-6" role='presentation' >
									<a href="#register" id="register-form-link" aria-controls="register" role="tab" data-toggle="tab">Register</a>
								</div>
							</div>
							<hr>
						</div>

						<div class="panel-body">
							<div class="row tab-content">
								<div class="col-lg-12 tab-pane active" role="tabpanel" id="login">
									<%= form_tag "/login", id: 'login-form', role: 'form', style: "display:block;" do %>
										<div class="form-group">
											<input type="email" name="email" tabindex="1" class='form-control' placeholder='Email' id='login-email' %>
										</div>
										<div class="form-group">
											<input type="password" name="password" tabindex="2" class="form-control" placeholder="Password">
										</div>
										<div class="form-group">
											<div class="row">
												<div class="col-sm-6 col-sm-offset-3">
													<input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login" value="Log In">
												</div>
											</div>
										</div>
										<div class="form-group">
											<div class="row">
												<div class="col-lg-12">
												</div>
											</div>
										</div>
									<% end %>
								</div>
								
								<div class="col-lg-12 tab-pane" role="tabpanel" id="register">
									<%= form_for user, {id: 'register-form', role: 'form', style: 'display:block;'} do |form| %>
										<div class="form-group">
											<%= form.text_field :name, {id: :user_name, class: 'form-control', placeholder: 'Name'} %>
										</div>
										<div class="form-group">
											<%= form.email_field :email, {id: :user_email, class: 'form-control', placeholder: 'Email'} %>
										</div>
										<div class="form-group">
											<%= form.password_field :password, {id: :user_password, class: 'form-control', placeholder: 'Password'} %>
										</div>
										<div class="form-group">
											<%= form.password_field :password_confirmation, {id: :user_password_confirmation, class: 'form-control', placeholder: 'Password Confirmation'} %>
										</div>
										<div class="form-group">
											<div class="row">
												<div class="col-sm-6 col-sm-offset-3">
													<%= form.submit name: 'register-submit', id: 'register-submit', tabindex: '4', class: 'form-control btn btn-register', value: 'Register' %>
												</div>
											</div>
										</div>
									<% end %>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<div class="container" id="insta" > 
		<a href='https://www.instagram.com/trekcheque/' target="_blank"><i class="fa fa-instagram fa-3x"></i></a>

			<!-- SnapWidget -->
		<script src="https://snapwidget.com/js/snapwidget.js"></script>
		<iframe src="https://snapwidget.com/embed/519980" class="snapwidget-widget" allowTransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden; width:100%; "></iframe>
	</div>

</body>

<footer>
	<div id="scroll-to-top">
			<span onclick="scrollto('top-half');"><i class="fa fa-chevron-circle-up"></i></span>
	</div>
</footer>

app/views/users/new.html.erb
<%= render 'login_form', user: @user %>

app/views/users/show.html.erb
<%= render 'layouts/nav_bar' %>
<p id="notice"><%= notice %></p>
<body>

  <h1 id="user-header">
    <strong>
      <%= @user.name %>
    </strong>
  </h1>

  <div class="user-email">
    <strong>Email:</strong>
    <%= @user.email %>
  </div>

  <div class="container-fluid">
    <div class="trip-grid">
        <% @trips_of_user.each do |trip| %>
        <div class="trip-box">
          <%= link_to trip_path(trip.id) do %>  
          <div class="trip-link">
            <strong><span style="font-size: 2rem;"><%= trip.name %></span></strong><br>
            <%= trip.start_date.strftime("%B %d, %Y") %><br>to<br><%= trip.end_date.strftime("%B %d, %Y") %>
            <br>
            <% if trip.start_location && trip.end_location%>
              <%= trip.start_location %> to <%= trip.end_location %>      
            <% end %>
            <br>
            <br>
            Friends on the trip:<br>
            <% trip.attendees.each do |attendee| %>
              <% friend = User.find(attendee.user_id) %>
              <%= friend.name %>
            <% end %>
            <br>
            <% if trip.type_of_trip %>
              <% if trip.type_of_trip == "Weekend Getaway" %>
                <%= image_tag("Weekend-Getaway.jpg", width: "200", style: "border: 1px solid #00415d; border-radius: 5px;")%>
              <% end %>
              <% if trip.type_of_trip == "Bachelorette" %>
                <%= image_tag("Bachelorette-party.jpg", width: "200", style: "border: 1px solid #00415d; border-radius: 5px;")%>
              <% end %>
              <% if trip.type_of_trip == "Adventure" %>
                <%= image_tag("Adventure.jpg", width: "200", style: "border: 1px solid #00415d; border-radius: 5px;")%>
              <% end %>
              <% if trip.type_of_trip == "Road Trip" %>
                <%= image_tag("road-Trip.jpg", width: "200", style: "border: 1px solid #00415d; border-radius: 5px;")%>
              <% end %>
              <% if trip.type_of_trip == "Boys Trip" %>
                <%= image_tag("boys-trip.jpg", width: "200", style: "border: 1px solid #00415d; border-radius: 5px;")%>
              <% end %>
              <% if trip.type_of_trip == "Other" %>
                <%= image_tag("other.jpeg", width: "200", style: "border: 1px solid #00415d; border-radius: 5px;")%>
              <% end %>
            <% end %>
          <% end %>
          </div>
        </div>
        <% end %>
    </div>
  </div>
</body>
      