config/routes.rb
Rails.application.routes.draw do

  root to: 'users#new'

  # serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
   resources :trips, param: :trip_id
   resources :messages  

  # if using update probably use patch? only changes the one field
  # have only got create and destroy attendees within the trip 
  resources :trips, except: [:index] do
    resources :attendees, only: [:create, :destroy]
    resources :messages, only: [:create, :destroy]

    resources :expenses, except: [:index, :new] do  
      resources :payees, only: [:create, :destroy]
      member do 
        get :inline_edit
      end
    end
  end
  
    # resources :sessions, except: [:index, :edit, :update]
  
    #users/new(register), users/edit(update email, etc.), users/show(user homepage)
    resources :users, only: [:new, :create, :edit, :show] 
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   get '/login' => 'users#new'
   post '/users' => 'users#create'
  
  #  get '/login' => 'sessions#new'
   post '/login' => 'sessions#create'
   get '/logout' => 'sessions#destroy'
  
  end

app/models/attendee.rb
class Attendee < ApplicationRecord

  monetize :balance_cents, numericality: true

  belongs_to :trip
  belongs_to :user

end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :set_attendee, only: [:show, :edit, :update, :destroy]
  before_action :set_trip, only: [:create, :destroy]
  before_action :authorize
 
  # GET /attendees
  # GET /attendees.json
  def index
    @attendees = Attendee.all
    @attendees_ids = []
    @attendees.each do |a|
      @attendees_ids.push(a.user_id)
    end
  end

  # GET /attendees/new
  def new
    @attendee = Attendee.new
  end

  # POST /attendees
  # POST /attendees.json
  def create
    params.each do |key, value|
    end

    @trips = Trip.all
    @attendee = Attendee.new(attendee_params)
    @attendee.trip_id = params[:trip_id]
    @attendee.user_id = current_user.id
    @attendee.balance = 0
    @attendees = Attendee.where(trip_id: params[:trip_id])
    @trip_length_night = (@trip.end_date - @trip.start_date).to_i
    @price_per_night = @trip.price_per_night
    @total_cost = @price_per_night.to_i * @trip_length_night.to_i

    if @attendee.save
      @total_confirmed_accomodation_cost_per_person = @total_cost.to_i / @attendees.size
      @trip.update_attribute(:total_confirmed_cost, @total_confirmed_accomodation_cost_per_person)
      redirect_to @trip, notice: 'A new guest has joined your trip!'
    else
      render json: @attendee.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /attendees/1
  # PATCH/PUT /attendees/1.json
  def update
    respond_to do |format|
      if @attendee.save
        format.html { redirect_to @trip, notice: 'Attendee was successfully created.' }
        format.json { render :show, status: :created, location: trip_path }
      else
        format.html { redirect_to @trip, notice: 'Attendee not successfully created.' }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendees/1
  # DELETE /attendees/1.json
  def destroy
    @attendees = Attendee.where(trip_id: params[:trip_id])
    @trip_length_night = (@trip.end_date - @trip.start_date).to_i
    @price_per_night = @trip.price_per_night
    @total_cost = @price_per_night.to_i * @trip_length_night.to_i
    @attendee.destroy
    if @attendee.destroy
      @attendees = Attendee.where(trip_id: params[:trip_id])
      @trip_length_night = (@trip.end_date - @trip.start_date).to_i
      @price_per_night = @trip.price_per_night
      @total_cost = @price_per_night.to_i * @trip_length_night.to_i
      if @attendees.size > 0
      @total_confirmed_accomodation_cost_per_person = @total_cost.to_i / @attendees.size
      @trip.update_attribute(:total_confirmed_cost, @total_confirmed_accomodation_cost_per_person)
      else 
       @trip.update_attribute(:total_confirmed_cost, 0) 
      end
    end
    respond_to do |format|
      format.html { redirect_to @trip, notice: 'An attendee can no longer make the trip.' }
      format.json { head :no_content }
    end
  end

  private
    def set_trip
      @trip = Trip.find(params[:trip_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_attendee
      @attendee = Attendee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendee_params
      params.permit(:trip_id, :user_id, :balance)
    end
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/views/attendees/_attendees_table.html.erb
<h3>Balance</h3>
<% if @attendees.count < @trip.number_of_possible_attendees%>
  <% if @attendees_ids.exclude? current_user.id %>
    <tr><%= button_to "Join Trip!", trip_attendees_path(@trip, current_user), method: :post %></tr>
  <% end %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name(s)</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attendees.each do |attendee| %>
      <tr>
        <td><i><%= attendee.user.name %></i></td>
        <td>$<%= attendee.balance %></td>
        <% if !@trip.started %>
        <% if current_user.id == attendee.user_id %>
          <td><button><%= link_to "Unconfirm", trip_attendee_url(@trip, attendee), method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
        <% end %>
        <% end %>
      </tr>
  </tbody>
  <% end %>
</table>

<br>

app/views/attendees/_form.html.erb
<%= form_with(model: attendee, local: true) do |form| %>
  <% if attendee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attendee.errors.count, "error") %> prohibited this attendee from being saved:</h2>

      <ul>
      <% attendee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :trip_id %>
    <%= form.text_field :trip_id, id: :attendee_trip_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :attendee_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>