config/routes.rb
Rails.application.routes.draw do

  root to: 'users#new'

  # serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
   resources :trips, param: :trip_id
   resources :messages  

  # if using update probably use patch? only changes the one field
  # have only got create and destroy attendees within the trip 
  resources :trips, except: [:index] do
    resources :attendees, only: [:create, :destroy]
    resources :messages, only: [:create, :destroy]

    resources :expenses, except: [:index, :new] do  
      resources :payees, only: [:create, :destroy]
      member do 
        get :inline_edit
      end
    end
  end
  
    # resources :sessions, except: [:index, :edit, :update]
  
    #users/new(register), users/edit(update email, etc.), users/show(user homepage)
    resources :users, only: [:new, :create, :edit, :show] 
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   get '/login' => 'users#new'
   post '/users' => 'users#create'
  
  #  get '/login' => 'sessions#new'
   post '/login' => 'sessions#create'
   get '/logout' => 'sessions#destroy'
  
  end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy, :inline_edit]
  before_action :update_balance, only: [:destroy, :update]

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.all
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
    @attendees = Attendee.where(trip_id: params[:id])
    @trip_attendees = @attendees.collect { |a| a.user }
    respond_to do |format|
        format.html {redirect_to @trip }
        format.json { render :show, status: :created, location: trip_expenses_path }
    end
  end

  # POST /expenses
  # POST /expenses.json
  def create
    params.each do |key, value|
    end

    @expense = Expense.new(expense_params)
    @expense.trip_id = params[:trip_id]
    @trip = Trip.find(params[:trip_id].to_i)
    @amount = @expense.amount

    # create hash to store split portions for each user
    split_hash = Hash.new()

    if params[:split_type] == "split_by_amount"
      passed_split = params[:expense][:payee][:split]
      portions = []
      passed_split.each do |id, obj|
        portions.push(obj[:portion].to_f)
      end
      portion_sum = 0
      portions.each { |a| portion_sum += a }
      if portion_sum != @amount.to_f
        redirect_to @trip, notice: 'Error: expense amount does not equal sum of portions entered.' 
        return
      end
      passed_split.each do |id, obj|
        @expense.payees.new(user_id: id)
        split_hash[id] = Money.new(obj[:portion].to_f * 100, 'USD')
      end
    else
      @willing_payees = params[:expense][:payee][:user_id].select { |uid| uid.length > 0 }
      @payee_size = @willing_payees.size
      @willing_payees.each do |pid|
        @expense.payees.new(user_id: pid)
        split_hash[pid] = (@amount / @payee_size) #/
      end
    end

    respond_to do |format|
      if @expense.save
        # go through hash and calculate user's owed balance
        split_hash.each do |key, value|
          @user_id = key
          @payee_user = User.where(id: @user_id)
          @payee_user_ids = @payee_user.ids
          @attendee_user_for_finding_expense = Attendee.where(user_id: @payee_user_ids, trip_id: params[:trip_id].to_i)
          @attendee_user_for_finding_expense.each do |attendee_for_balance|
            attendee_for_balance.balance += value
            @attendee_balance = attendee_for_balance.balance
            attendee_for_balance.update_attribute(:balance, @attendee_balance)
          end
        end

        # deduct amount paid by expense user
        @attendee_payer_of_expense = Attendee.where(user_id: @expense.user_id, trip_id: params[:trip_id].to_i).first
        @payer_balance = @attendee_payer_of_expense.balance - @expense.amount
        @attendee_payer_of_expense.update_attribute(:balance, @payer_balance)
        format.html { redirect_to @trip, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: trip_expenses_path }
      else
        format.html { redirect_to @trip, notice: 'Expense not successfully created.' }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    @expense = Expense.find(params[:id])

    if @expense
      @expense.destroy
    end

    @trip = Trip.find(params[:trip_id].to_i)

    params.each do |key, value|
    end
    
    @updated_expense = Expense.new(expense_params)

    @updated_expense.trip_id = params[:trip_id]
    @trip = Trip.find(params[:trip_id].to_i)
    @amount = @updated_expense.amount

    # create hash to store split portions for each user
    split_hash = Hash.new()
    if params[:split_type] == "split_by_amount"
      passed_split = params[:expense][:payee][:split]
      portions = []
      passed_split.each do |id, obj|
        portions.push(obj[:portion].to_f)
      end
      portion_sum = 0
      portions.each { |a| portion_sum += a }
      if portion_sum != @amount.to_f
        redirect_to @trip, notice: 'Error: expense amount does not equal sum of portions entered.' 
        return
      end
      passed_split.each do |id, obj|
        @updated_expense.payees.new(user_id: id)
        split_hash[id] = Money.new(obj[:portion].to_f * 100, 'USD')
      end
    else
      @willing_payees = params[:expense][:payee][:user_id].select { |uid| uid.length > 0 }
      @payee_size = @willing_payees.size
      @willing_payees.each do |pid|
        @updated_expense.payees.new(user_id: pid)
        split_hash[pid] = (@amount / @payee_size) #/
        # TODO: this is kinda cavalier about the possibility of errors.  ha ha!
      end
    end

    respond_to do |format|
      if @updated_expense.save
        # go through hash and calculate user's owed balance
        split_hash.each do |key, value|
          @user_id = key
          @payee_user = User.where(id: @user_id)
          @payee_user_ids = @payee_user.ids
          @attendee_user_for_finding_expense = Attendee.where(user_id: @payee_user_ids, trip_id: params[:trip_id].to_i)
          @attendee_user_for_finding_expense.each do |attendee_for_balance|
            attendee_for_balance.balance += value
            @attendee_balance = attendee_for_balance.balance
            attendee_for_balance.update_attribute(:balance, @attendee_balance)
          end
        end
        # deduct amount paid by expense user
        @attendee_payer_of_expense = Attendee.where(user_id: @updated_expense.user_id, trip_id: params[:trip_id].to_i).first
        @payer_balance = @attendee_payer_of_expense.balance - @updated_expense.amount
        @attendee_payer_of_expense.update_attribute(:balance, @payer_balance)
        format.html { redirect_to @trip, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: trip_expenses_path }
      else
        format.html { redirect_to @trip, notice: 'Expense not successfully created.' }
        format.json { render json: @updated_expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @trip = Trip.find(params[:trip_id].to_i)
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to @trip, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def inline_edit
    # @attendees = Attendee.where(trip_id: params[:id])
    #@attendees = @expense.payees.all
    @attendees = Attendee.where(trip_id: params[:trip_id])
    @trip_attendees = @attendees.collect { |a| a.user }
    respond_to do |format|
      format.js { render :file => "trips/inline_edit.js.erb" }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
      @trip = Trip.find(params[:trip_id].to_i)
    end
   
    def update_balance
      @willing_payees = @expense.payees.all
      @amount = @expense.amount
      @payee_size = @willing_payees.count
      @payee_owes = (@amount / @payee_size) 
      @willing_payees.each do |payee|
        @user_id = payee.user_id
        @payee_user = User.where(id: @user_id)
        @payee_user_ids = @payee_user.ids
        @attendee_user_for_finding_expense = Attendee.where(user_id: @payee_user_ids, trip_id: params[:trip_id].to_i)
        @attendee_user_for_finding_expense.each do |attendee_for_balance|
          attendee_for_balance.balance -= @payee_owes
          @attendee_balance = attendee_for_balance.balance
          attendee_for_balance.update_attribute(:balance, @attendee_balance)
        end
      end
      @attendee_payer_of_expense = Attendee.where(user_id: @expense.user_id, trip_id: params[:trip_id].to_i).first
      @gets_back = (@payee_owes * @payee_size)
      @payer_balance = @attendee_payer_of_expense.balance + @gets_back
      @attendee_payer_of_expense.update_attribute(:balance, @payer_balance)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:trip_id, :user_id, :amount, :description, payees_attributes: [:id, :user_id, :expense_id])
    end

end
        

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_expense_list.html.erb
<script>
  function toggleUpdateForm() {
      $('#expense-form-container').toggle("blind", 1000);
  };
</script>

<body>
  <h3> Expense List </h3>

  <div class="container-fluid">
    <table class="expenses-table">
      <thead>
        <tr>
          <th style="width: 20%;">Paid by:</th>
          <th style="width: 20%;">Amount</th>
          <th style="width: 50%;">Description</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <% @expenses.each do |expense| %>
        <tbody>
          <div class="expense-container">
            <tr>
              <td><%= expense.user.name %></td>
              <td>$ <%= expense.amount %></td>
              <td><%= expense.description %></td>
              <% if @attendees_ids.include? current_user.id %>
                <% if !@trip.ended %>
                  <td><%= link_to  [:inline_edit, @trip, expense], onclick: "toggleUpdateForm()", datatarget: expense.id, remote: true do %><i class="fa fa-edit" style="font-size:1.3em;"></i><% end %></td>
                  <td><%= link_to  trip_expense_url(@trip, expense), method: :delete, data: { confirm: 'Are you sure?' } do %><i class="fa fa-trash" style="font-size:1.3em;"></i><% end %></td>
                <% end %>
              <% end %>
            </tr>
          </div>
        </tbody>
      <% end %>
    </table>

  <div class="container-fluid" id="editexpenseform">
    <br>
    <div class="row-fluid" id="expense-form-container" style="display: none;">
      <div class="span8 well">
        <ul class="nav nav-tabs">
          <li class="active"> <a href="#editeven" data-target="#editeven" data-toggle="tab">Split evenly</a></li>
          <li><a href="#editportion" data-target="#editportion" data-toggle="tab">By Amount</a></li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane active fade in" id="editeven">
            <div id="expense-edit-partial">
            </div>
          </div>
                  
        <div class="tab-pane" id="editportion">
          <div id="expense-edit-options-partial">
         </div>
        </div>
      </div>
    </div>
  </div>
  </div>
  </div>
  <br>
</body>

app/views/expenses/_form.html.erb
<%= form_with(model: @expense, local: true) do |form| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this @expense from being saved:</h2>

      <ul>
        <% @expense.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.select(:user_id) do %>
      <%= options_from_collection_for_select(@trip_attendees, :id, :name) %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount, id: :expense_amount %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :expense_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/expenses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Expenses</h1>

<table>
  <thead>
    <tr>
      <th>Trip</th>
      <th>User</th>
      <th>Amount</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.trip %></td>
        <td><%= expense.user %></td>
        <td><%= expense.amount %></td>
        <td><%= expense.description %></td>
        <td><%= link_to 'Show', expense %></td>
        <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
        <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expense', new_expense_path %>

app/views/expenses/new.html.erb
<h1>New Expense</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Back', expenses_path %>