config/routes.rb
Rails.application.routes.draw do

  root to: 'users#new'

  # serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
   resources :trips, param: :trip_id
   resources :messages  

  # if using update probably use patch? only changes the one field
  # have only got create and destroy attendees within the trip 
  resources :trips, except: [:index] do
    resources :attendees, only: [:create, :destroy]
    resources :messages, only: [:create, :destroy]

    resources :expenses, except: [:index, :new] do  
      resources :payees, only: [:create, :destroy]
      member do 
        get :inline_edit
      end
    end
  end
  
    # resources :sessions, except: [:index, :edit, :update]
  
    #users/new(register), users/edit(update email, etc.), users/show(user homepage)
    resources :users, only: [:new, :create, :edit, :show] 
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   get '/login' => 'users#new'
   post '/users' => 'users#create'
  
  #  get '/login' => 'sessions#new'
   post '/login' => 'sessions#create'
   get '/logout' => 'sessions#destroy'
  
  end

app/views/layouts/_nav_bar.html.erb
<head><script src="https://use.fontawesome.com/ac442f7ad2.js"></script>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-brand-name"><i class="fa fa-car"></i><%=link_to 'Trek Cheque', login_path%></div>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
      <div class="right">
        <ul class="nav navbar-nav navbar-left">
          <li class="nav-item">
            <% if current_user %>
              <li class="nav-link"><%= render './trips/create_trip_form', new_trip: @new_trip, trip: @trip, trip_types: @trip_types %></li>
            <% end %>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <% if current_user %>
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown">
                Signed in as <%= current_user.name %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li class="dropdown-item"><%=link_to 'Profile Page', user_path(current_user.id)%></li>
                <li class="dropdown-item"><%=link_to 'Logout', logout_path %></li>
              </ul>
            <% else %>
              <li class="nav-item">
                <a class="nav-link" href="login_path">Login/Register</a>
              </li>
            <% end %>
          </li>
        </ul>
        </div>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trekcheque</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E="
      crossorigin="anonymous">
    </script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>